name: Build documentation


on:
  - push
  #temp, replace to weekly later

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blog
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GHA_TOKEN }}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.07.1

      - name: Pin OASIS
        run: opam pin add oasis https://github.com/BinaryAnalysisPlatform/oasis.git

      - name: Checkout bap
        uses: actions/checkout@v2
        with:
          repository: BinaryAnalysisPlatform/bap
          path: bap.master

      - name: Pin BAP
        run: opam pin add bap bap.master --no-action

      - name: Install system dependencies
        run: opam depext -u bap

      - name: Install opam dependencies
        run: |
            opam install bap --deps-only
            opam install omake

      - name: Install Bap
        run: |
          cd bap.master
          opam exec -- ./configure-omake
          opam exec -- make
          opam exec -- make reinstall
          cd ../

      - name: Build Documentation
        run: |
          sudo apt-get install emacs-nox man2html --yes
          opam install odig --yes
          opam exec -- make -C bap.master clean
          opam exec -- make -C bap.master doc

      - name: update and push
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email "action-noreply@github.com"
          cp -r  bap.master/doc/man1 bap/api/
          cp -r  bap.master/doc/man3 bap/api/
          cp -r  bap.master/doc/lisp bap/api/
          cp -rL bap.master/doc/odoc bap/api/
          git add bap/api
          git commit -m "updates documentation" > /dev/null
          git push origin adds-actions # <<<<< REPLACE TO master
